import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import mammoth from "mammoth";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const docxPath = path.join(root, "Oleg_Velikanov_CV.docx");
const outText = path.join(root, "src", "profile", "cv-extracted.gen.ts");
const outHtml = path.join(root, "src", "profile", "cv-extracted-html.gen.ts");

if (!fs.existsSync(docxPath)) {
  console.error("Missing Oleg_Velikanov_CV.docx in project root.");
  process.exit(1);
}

const { value: rawText } = await mammoth.extractRawText({ path: docxPath });
const text = (rawText || "").trim();
if (!text) {
  console.error("Extracted CV text is empty.");
  process.exit(1);
}

const htmlResult = await mammoth.convertToHtml({ path: docxPath });
const html = (htmlResult.value || "").trim();
if (!html) {
  console.error("Extracted CV HTML is empty.");
  process.exit(1);
}

const header =
  "/** Auto-generated by npm run cv:extract from Oleg_Velikanov_CV.docx — do not edit. */\n";
fs.writeFileSync(outText, header + `export const CV_SOURCE_TEXT = ${JSON.stringify(text)};\n`, "utf8");
fs.writeFileSync(outHtml, header + `export const CV_SOURCE_HTML = ${JSON.stringify(html)};\n`, "utf8");
console.log("Wrote", outText, `(${text.length} chars text)`);
console.log("Wrote", outHtml, `(${html.length} chars html)`);
